### PR TITLE
Update README.rst

### PR DESCRIPTION
**Pull request by femtotrader**
Add parentheses for Python 3 support

### CODE REVIEW

**Comment by trickvi** [comment]
Thanks for this @femtotrader. Because I'm so backwards and still not using python 3, it's good that people help out like this to make sure python 3 is supported. It makes me happy :smile:

**Comment by femtotrader** [comment]
I'm using Anaconda Python. My default Python version is 3 and I can switch to Python 2 easily. 

You can also use Python 2 as default Python version and switch to Python 3 when you want
http://continuum.io/blog/anaconda-python-3

**Comment by trickvi** [comment]
Yeah. I'm just being lazy. I need to switch at some point.

**Comment by femtotrader** [comment]
We all have, as Python developers, the "duty" to switch because Python 3 have many advantages over Python 2 (unicode, ...) https://wiki.python.org/moin/Python2orPython3

**Pull request merged**
