### PR TITLE
Recognize "PDDL-1.0" as a valid license id

### PR DESCRIPTION
**Pull request by LuizArmesto**
Data Packages Spec [1] uses "PDDL-1.0" as an example, so I think it is a valid id.

[1] http://dataprotocols.org/data-packages/

### CODE REVIEW

**Comment by tryggvib** [comment]
Hey @LuizArmesto 

Thanks a lot for this. Could I ask you to go through and make sure we're up to date with all the licenses here: http://licenses.opendefinition.org/licenses/groups/all.json

These are the licenses and shorthand recognised in the open definition work and what data packages conform with.

**Comment by LuizArmesto** [comment]
Sure. I will take care of it soon.

**Comment by LuizArmesto** [comment]
Also related to #43

**Comment by trickvi** [comment]
Hi @LuizArmesto I hadn't noticed the commit there!!! Sorry for taking so long. Will update straight away.

**Pull request merged**
